# https://docs.gradle.org/current/userguide/version_catalogs.html

[versions]
benchmark = "1.5.0-alpha01"
jmh = "1.37"
lint = "31.5.2"
room = "2.6.1"

[libraries]
android-tools-gradle = { module = "com.android.tools.build:gradle", version = "9.0.0" }
android-tools-lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
android-tools-lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "benchmark" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version = "2.8.4" }
androidx-paging = { module = "androidx.paging:paging-runtime", version = "3.3.2" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-test-ext = { module = "androidx.test.ext:junit", version = "1.2.1" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.6.1" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.6.2" }
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
junit-junit = { module = "junit:junit", version = "4.13.2" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.10.2" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version = "2.3.0" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version = "1.8.1" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.11.0" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "5.3.1" }
robolectric-android-all = { module = "org.robolectric:android-all", version = "12.1-robolectric-8229987" }
xerial-sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version = "3.51.1.0" }

[bundles]

[plugins]
androidx-benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
cash-licensee = { id = "app.cash.licensee", version = "1.14.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.7" }
jmh = { id = "me.champeau.jmh", version = "0.7.3" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.4" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.4" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.0" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
qodana = { id = "org.jetbrains.qodana", version = "0.1.12" }
undercouch-download = { id = "de.undercouch.download", version = "5.4.0" }
