# https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

[versions]
benchmark = "1.2.4"
jmh = "1.37"
lint = "31.5.2"
room = "2.6.1"

[libraries]
android-tools-gradle = { group = "com.android.tools.build", name = "gradle", version = "8.5.2" }
android-tools-lint = { group = "com.android.tools.lint", name = "lint", version.ref = "lint" }
android-tools-lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "benchmark" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.13.1" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.8.4" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version = "3.3.2" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-test-rules = { group = "androidx.test", name = "rules", version = "1.6.1" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.6.2" }
findbugs-jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version = "3.0.2" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
junit-junit = { group = "junit", name = "junit", version = "4.13.2" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version = "5.10.2" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version = "2.0.10" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit" }
kotlinx-coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version = "1.8.1" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
mockito-core = { group = "org.mockito", name = "mockito-core", version = "5.11.0" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "5.3.1" }
robolectric-android-all = { group = "org.robolectric", name = "android-all", version = "12.1-robolectric-8229987" }

[bundles]

[plugins]
androidx-benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
cash-licensee = { id = "app.cash.licensee", version = "1.6.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.7" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.6" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.10-1.0.24" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.0" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
qodana = { id = "org.jetbrains.qodana", version = "0.1.12" }
undercouch-download = { id = "de.undercouch.download", version = "5.4.0" }
